### ISSUE TITLE
ArrayIndexOutOfBoundsException (-33) in DataDeSerializer

### ISSUE THREAD

**Issue by andronix3** [tzaeschke/zoodb#91] opened 2017-01-14 08:31 UTC
java.lang.ArrayIndexOutOfBoundsException: -33
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at org.zoodb.internal.DataDeSerializer.readClassInfo(DataDeSerializer.java:973)
	at org.zoodb.internal.DataDeSerializer.deserializeObjectNoSco(DataDeSerializer.java:544)
	at org.zoodb.internal.DataDeSerializer.deserializeFields1(DataDeSerializer.java:384)
	at org.zoodb.internal.DataDeSerializer.readObjPrivate(DataDeSerializer.java:309)
	at org.zoodb.internal.DataDeSerializer.readObject(DataDeSerializer.java:185)
	at org.zoodb.internal.server.index.ObjectPosIterator.findNext(ObjectPosIterator.java:69)
	at org.zoodb.internal.server.index.ObjectPosIterator.next(ObjectPosIterator.java:62)
	at org.zoodb.internal.server.index.ObjectPosIterator.next(ObjectPosIterator.java:1)
	at org.zoodb.internal.util.MergingIterator.next(MergingIterator.java:79)
	at org.zoodb.internal.util.SynchronizedROIterator.next(SynchronizedROIterator.java:74)
	at org.zoodb.jdo.impl.QueryImpl.applyQueryOnExtent(QueryImpl.java:533)
	at org.zoodb.jdo.impl.QueryImpl.runQuery(QueryImpl.java:577)
	at org.zoodb.jdo.impl.QueryImpl.execute(QueryImpl.java:671)
	at com.smartgr.profiler.ZPlayer.getPlayerByName(ZPlayer.java:211)

I implementing Poker Player Profiling App. 
If I add a single Hand History to DB, everything is working just fine.
If I run over all Hand Histories in a directory, after third Hand History it keeps to throw above error, because  id is negative (-33).

**Comment by tzaeschke** [comment] 2017-01-14 16:11
Hi, could you provide a small sample program that reproduces the problem?
Or could you at least describe what your schema looks like, i.e. could you post the persistent classes that you are using?

**Comment by andronix3** [comment] 2017-01-14 18:24
May I send files to you by email?

**Comment by tzaeschke** [comment] 2017-01-14 21:19
sure, no problem.

**Comment by tzaeschke** [comment] 2017-01-17 15:01
Problem could not be reproduced yet. The following is known:
- The OP could solve it by doing a commit() before querying
- Thus: The query failed (presumably) on an object that was just created, thus it was not even committed. Why was it accessing the disk then? Presumably to query all other Objects, there was no index....
- The problem occurred only after ingesting a lot of object, apparently during the 3rd 'phase'
- All ingestion occurred with the same PM (unless the 'phases' used different PMs?). There were no concurrent PMs.
- No schema evolution was performed
- No index in the database.
- The erroneous -33 did not turn up in the DataSerializer. This may suggest that the DataDeserializer was reading at the wrong place or the DataSerializer was writing data incorrectly.
- The problem occurred during a query while deserializing an object. It failed during de-serialization of the first field (A String field), while reading the type information of the String's magic number (Other question: why is there type information with the magic number? -> Cannot be null...)

Possible causes:
- Deserializer (Serializer?) is wrong. Check: Why do we read type information for String's magic numbers? However, this would fail far more often if it was incorrect.
- Unicode Problems. ZooDB is currently storing only 1byte per character. Could this pose a problem? 
- Cache-Garbage-Collection? The problem occurred only after ingesting >100000 objects. Maybe the GC cleaned up the cache and caused some confusion? Such as reading an object from the wrong page?

**Comment by tzaeschke** [comment] 2017-01-24 20:39
It turns out that the Query and Extent classes allow under certain circumstances to access deserialization code when a PM is already closed. Specifically this could happen if there was an index defined in the database. The following tests reproduce the issue, it has been fixed with the commit above.
`Test_070_Query.testQueryOnClosedPM_Issue91()` and `Test_060_Extents.testExtentOnClosedPM_Issue91()`. 

It is likely that this was the same problem that the OP had, because the OP reported in a separate email that there was a query that was mistakenly used after the PM was closed.

Despite reporting a deserialization error, this error did not cause database corruption. Instead, the DB appears inconsistent because the closed PM maintains an outdated index of the database.

**Closed** 2017-02-19 20:21 UTC
Labels: bug, internal
