### ISSUE TITLE
DataSerializer fails on empty arrays

### ISSUE THREAD

**Issue by slavap** [tzaeschke/zoodb#98] opened 2017-05-15 22:05 UTC
The following code fails with NPE exception:

```java
public abstract class Content extends ZooPC {
    Property[] properties;
}

public class Folder extends Content {
    String name;
    public Folder() {}
}

public class Property extends ZooPC {
}

public class StringProperty extends Property {
    String value;
    public StringProperty() {}
}

{
    pm.currentTransaction().begin();
    Folder f = new Folder();
    f.name = "abc";
    f.properies = new Property[] {};
    f.zooActivateWrite();
    pm.makePersistent(f);
    pm.currentTransaction().commit();
}
```

The problem in DataSerializer.writeClassInfo(Class<?> cls, Object val) method:
```java
        //for persistent classes, store oid of schema. Fetching it should be fast, it should
        //be in the local cache.
        if (isPersistentCapable(cls)) {
            out.writeByte(SerializerTools.REF_PERS_ID);
            if (val != null) {
            	long soid = ((ZooPC)val).jdoZooGetClassDef().getOid();
            	out.writeLong(soid);
            } else {
            	long soid = cache.getSchema(cls, node).getOid(); <<< HERE if getSchema() returns null then out.writeLong(SerializerTools.REF_NULL_ID) should be used, or perhaps getSchema() is not needed at all and REF_NULL_ID should be always written.
            	out.writeLong(soid);
            }
            return;
        }
```

**Comment by tzaeschke** [comment] 2017-05-16 18:12
Could you give me some more information, such as

- How is the database schema initialized?
- Are you using schema-auto-creation?
- Are you using any additional settings when on PersistenceManagerFactory, PersistenceManager, Transaction?
- Which version of ZooDB have you tested?

So far I tested it with devTZ_main branch, and I get either no Exception (predefined schema) or a JDOUserException (auto-create schema). I don't see an NPE at the moment. 

Also, I noticed that you are missing `zooActivateWrite()` before setting the fields. This is usually done in the setter() methods. However, adding/removing `zooActivateWrite()` doesn't seem to make a difference in terms of Exceptions or not...

**Comment by slavap** [comment] 2017-05-16 19:16
Yes, I'm using schema-auto-creation.
I will create test project for this bug.
I'm working with zoodb 0.4.9
And I was under impression that it doesn't matter when f.zooActivateWrite() is called, so in my understanding before or after are doing the same thing.

**Comment by slavap** [comment] 2017-05-16 22:02
Unfortunatelly, I cannot assign zip in comments, so I've renamed zip to png. Download, rename back to zip, and execute runme.cmd, then you'll get NPE. Let me know if you need any additional info.
![zoodbbugs](https://cloud.githubusercontent.com/assets/4129763/26130259/acc5ca48-3a48-11e7-9130-19a70a892a68.png)

**Comment by tzaeschke** [comment] 2017-05-17 20:43
Thanks, I can reproduce it now. I'll have to investigate why it doesn't happen in my normal test environment.

`zooActivateWrite()` has several purposes. On new objects, it probably does not matter _when_ it is called. However, for example, for objects coming from the database (when their state is 'hollow'), calling `zooActivateWrite()` will read the object from the database and overwrite any changes to the object that may have occurred since the last commit or rollback. The save option is to call `zooActivateWrite()` in the beginning of each method that modifies an object, for example in every setter method. The method has very little overhead once the object is loaded and flagged as 'dirty'.

**Comment by tzaeschke** [comment] 2017-05-17 21:04
Just in case, a simple workaround is to define the schema manually, at least for the `Property` class by doing the following before the main transaction:

```
        pm.currentTransaction().begin();
        ZooSchema schema = ZooJdoHelper.schema(pm);
        schema.addClass(Property.class);
        pm.currentTransaction().commit();
```

Also, with `schema.getClass(...)` allows you to check whether a schema is already defined.

This qualifies for the ongoing bug bounty. If you are interested, could you contact me via zoodb(AT)gmx(DOT)de to organize the bounty?

**Comment by slavap** [comment] 2017-05-17 22:00
@tzaeschke Thanks. I've workaround this problem by just storing fake StringProperty with my main/root folder, after that following empty Property arrays are stored just fine. But your workaround looks good to me as well. Will send you email for organizing the bounty, really surprised by this fact.

**Comment by tzaeschke** [comment] 2017-05-25 20:58
Should be fixed now on devTZ_main branch. I'll look at the other issue tomorrow. Thanks for reporting!

**Closed** 2017-05-26 11:44 UTC
